In [95]:
from sql_functions import get_dataframe
import pandas as pd
import numpy as np
# Import packages 
import numpy as np
import pandas as pd

In [96]:
schema = "bgg_data"


df_family = get_dataframe(f"SELECT * FROM {schema}.family_bgg")

df_main = get_dataframe(f"SELECT * FROM {schema}.unfiltered_main_stats_cleaned")

In [97]:
df_main

,id,yearpublished,min_players,max_players,playtime,min_playtime,max_playtime,min_age,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight
0,98401,2010.0,2.0,4.0,30.0,30.0,30.0,10,7.08333,3,15,0,1,3,2,2,1.5
1,98402,2011.0,2.0,5.0,30.0,30.0,30.0,8,6.34615,26,20,0,7,13,9,5,2.2
2,98406,2011.0,2.0,4.0,30.0,30.0,30.0,10,6.73333,9,16,3,0,0,3,1,1.0
3,98416,2007.0,2.0,4.0,50.0,50.0,50.0,8,6.80000,2,16,2,1,0,2,1,3.0
4,98417,2009.0,2.0,2.0,60.0,60.0,60.0,12,0.00000,0,10,1,2,2,0,1,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137142,298189,2020.0,3.0,7.0,120.0,30.0,120.0,7,0.00000,0,0,0,0,0,0,0,NaN
137143,298190,2020.0,3.0,6.0,30.0,30.0,30.0,12,6.66667,3,47,2,1,5,4,0,NaN
137144,298191,2022.0,2.0,5.0,80.0,30.0,80.0,8,0.00000,0,5,0,0,0,0,0,NaN
137145,298193,2020.0,2.0,6.0,20.0,10.0,20.0,10,7.38077,26,61,1,0,7,7,2,1.5
137146,298195,2020.0,1.0,4.0,120.0,60.0,120.0,14,6.66667,3,79,1,16,78,6,0,NaN

In [98]:
mask = df_main['id'] == 230802

df_main = df_main.drop_duplicates(subset='id')

In [99]:
df_kickstarter_bool = df_family.query('family_value == "kickstarter"')

In [100]:
df_kickstarter_bool.drop(['family_type','family_value','family_id'],axis=1,inplace=True)

/var/folders/rb/p48bcgy90nn3g9bz4kw5bh4w0000gn/T/ipykernel_6166/385456819.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_kickstarter_bool.drop(['family_type','family_value','family_id'],axis=1,inplace=True)

In [101]:
df_kickstarter_list = df_kickstarter_bool['id'].to_list()

In [102]:
df_kickstarter_list

[98443,
 98527,
 173005,
 173018,
 173024,
 173057,
 173058,
 173059,
 173070,
 173072,
 173073,
 173075,
 173093,
 173105,
 173108,
 173109,
 173110,
 173115,
 173117,
 173129,
 173130,
 173131,
 173148,
 344233,
 344235,
 344240,
 344247,
 344268,
 344269,
 344274,
 344280,
 344292,
 344308,
 344341,
 344345,
 244212,
 244231,
 244236,
 244241,
 244250,
 244258,
 244268,
 244271,
 244301,
 244302,
 244304,
 244305,
 244338,
 244352,
 244358,
 244367,
 339227,
 339251,
 339258,
 339296,
 339302,
 339336,
 339340,
 147420,
 147428,
 147431,
 147437,
 147445,
 147465,
 147505,
 147522,
 147552,
 147598,
 64826,
 239241,
 239242,
 239244,
 239246,
 239262,
 239277,
 239288,
 239290,
 239291,
 239292,
 269831,
 269887,
 269955,
 206664,
 206681,
 206757,
 206778,
 306621,
 306623,
 306634,
 306636,
 306637,
 306643,
 306650,
 306653,
 306676,
 306681,
 306682,
 306687,
 306709,
 306710,
 306712,
 306715,
 306717,
 306721,
 306722,
 306760,
 306779,
 306797,
 306798,
 13657,
 13726,
 265601,
 265620,
 265635,
 265645,
 265657,
 265691,
 265693,
 265734,
 265737,
 265738,
 265744,
 265756,
 265757,
 265771,
 265784,
 265785,
 265786,
 265795,
 365602,
 365603,
 365605,
 365608,
 365624,
 365638,
 365676,
 365715,
 365716,
 365725,
 365756,
 365761,
 70767,
 312800,
 312838,
 312859,
 312889,
 312901,
 312904,
 312911,
 312928,
 312943,
 312944,
 312946,
 312951,
 312959,
 312963,
 312968,
 312983,
 124545,
 124548,
 86414,
 212807,
 212817,
 212829,
 212901,
 212921,
 212924,
 212962,
 212971,
 713,
 293400,
 293404,
 293437,
 293523,
 293525,
 293547,
 293579,
 293586,
 293594,
 218642,
 218698,
 218700,
 218702,
 218703,
 218754,
 218755,
 218756,
 218758,
 218759,
 218762,
 218791,
 318622,
 318626,
 318643,
 318656,
 318661,
 318664,
 318709,
 318710,
 318740,
 159405,
 159407,
 159410,
 159432,
 159435,
 159447,
 159462,
 159469,
 159492,
 159501,
 159502,
 159503,
 159504,
 159508,
 159515,
 159517,
 159523,
 159525,
 159526,
 159531,
 159532,
 159577,
 190247,
 190266,
 190289,
 190301,
 190333,
 190387,
 110147,
 327228,
 327238,
 327242,
 327245,
 327266,
 327289,
 327302,
 327371,
 327384,
 327390,
 227212,
 227221,
 227229,
 227260,
 227267,
 227304,
 227314,
 227315,
 227353,
 256208,
 256212,
 256232,
 256238,
 256244,
 256249,
 256250,
 256251,
 256317,
 256334,
 256377,
 256391,
 256393,
 128484,
 356203,
 356207,
 356219,
 356230,
 356243,
 356279,
 356280,
 356281,
 356282,
 356289,
 356292,
 356307,
 356308,
 356309,
 356317,
 356356,
 43365,
 43396,
 161063,
 161064,
 161076,
 161118,
 161120,
 161121,
 161122,
 161123,
 161124,
 161137,
 269618,
 269710,
 269712,
 269726,
 269737,
 269745,
 269760,
 269798,
 261838,
 261887,
 261894,
 261895,
 261898,
 261900,
 261991,
 155411,
 155416,
 155440,
 155451,
 155465,
 155479,
 155484,
 155487,
 155494,
 155530,
 155582,
 361805,
 361826,
 361877,
 361882,
 361894,
 361896,
 361897,
 361904,
 361908,
 361921,
 361969,
 361973,
 361986,
 361994,
 314628,
 314664,
 314665,
 314747,
 314758,
 314759,
 2960,
 214673,
 62708,
 277611,
 277615,
 277631,
 277634,
 277659,
 277664,
 277668,
 277669,
 277670,
 277692,
 277700,
 277702,
 277716,
 277724,
 277776,
 277777,
 277785,
 277786,
 277787,
 248232,
 248248,
 248267,
 248268,
 248269,
 248271,
 248273,
 248304,
 248306,
 248308,
 248309,
 248310,
 248311,
 248312,
 248313,
 248319,
 248321,
 248322,
 248344,
 248366,
 248385,
 248389,
 281412,
 281420,
 281455,
 281457,
 281458,
 281460,
 281466,
 281467,
 281515,
 281524,
 281526,
 281549,
 281555,
 200825,
 200835,
 200853,
 200886,
 200890,
 200934,
 200954,
 200998,
 348207,
 348216,
 348237,
 348303,
 348325,
 136440,
 136511,
 136512,
 136513,
 136514,
 136515,
 136516,
 136517,
 136518,
 136519,
 136520,
 136558,
 136587,
 136594,
 300800,
 300848,
 300906,
 300927,
 300928,
 235246,
 235283,
 235285,
 235328,
 235342,
 235344,
 235360,
 235363,
 335204,
 335212,
 335239,
 335295,
 335320,
 335384,
 102107,
 102156,
 20295,
 182206,
 182214,
 182216,
 182228,
 182243,
 182252,
 182268,
 182270,
 182295,
 182314,
 182320,
 182351,
 182385,
 182387,
 182388,
 182397,
 182398,
 182399,
 1306,
 260202,
 260219,
 260227,
 260251,
 260264,
 260282,
 260314,
 260315,
 260323,
 260325,
 260354,
 260360,
 260384,
 260387,
 228855,
 228889,
 228892,
 228935,
 228944,
 228945,
 157014,
 157049,
 157053,
 157070,
 157085,
 157086,
 157088,
 157096,
 157166,
 157169,
 75322,
 360205,
 360216,
 360242,
 360257,
 360259,
 360276,
 360295,
 360313,
 360314,
 360315,
 360323,
 360360,
 328853,
 328854,
 328855,
 328866,
 328871,
 328890,
 328892,
 328970,
 328994,
 328999,
 195609,
 195621,
 195629,
 195696,
 195708,
 195794,
 322601,
 322619,
 322621,
 322622,
 322644,
 322647,
 322649,
 322656,
 322658,
 322673,
 322674,
 322685,
 322687,
 322694,
 322703,
 322704,
 322709,
 322720,
 322721,
 322725,
 322770,
 322781,
 222658,
 222724,
 222725,
 222732,
 222738,
 222739,
 222741,
 222758,
 253803,
 253807,
 253835,
 253861,
 253870,
 253913,
 253924,
 253937,
 353812,
 353839,
 353840,
 353847,
 353904,
 353908,
 353914,
 353928,
 353938,
 353943,
 353957,
 353978,
 163404,
 163432,
 163474,
 163526,
 163549,
 163562,
 163572,
 163596,
 236803,
 236820,
 236833,
 236854,
 236861,
 236876,
 236884,
 236885,
 236903,
 236927,
 236932,
 236933,
 236940,
 236946,
 236957,
 236999,
 336802,
 336811,
 336815,
 336817,
 336830,
 336832,
 336842,
 336844,
 336846,
 336848,
 336849,
 336868,
 336874,
 336891,
 336893,
 336931,
 336946,
 336958,
 336959,
 336962,
 336986,
 149057,
 149067,
 149069,
 149092,
 149093,
 149097,
 149111,
 149112,
 149113,
 149119,
 149120,
 149121,
 149137,
 149155,
 149156,
 149160,
 149161,
 149163,
 149165,
 149169,
 179800,
 179803,
 179804,
 179808,
 179814,
 179815,
 179819,
 179841,
 179846,
 179876,
 179896,
 179898,
 179912,
 179916,
 179929,
 179930,
 179933,
 179942,
 179996,
 341636,
 341679,
 341688,
 341690,
 341691,
 341692,
 341693,
 341694,
 341705,
 341763,
 341772,
 341787,
 241626,
 241627,
 241658,
 241724,
 241726,
 241728,
 241756,
 283029,
 283137,
 283151,
 283152,
 283155,
 203213,
 203215,
 96026,
 134033,
 134069,
 134103,
 134191,
 303265,
 303331,
 303370,
 303371,
 303375,
 303376,
 303378,
 303380,
 145028,
 145030,
 145031,
 145032,
 145033,
 145034,
 145036,
 145037,
 145038,
 145039,
 145040,
 272215,
 272223,
 272237,
 272253,
 272254,
 272394,
 272395,
 272396,
 272399,
 230615,
 230642,
 230646,
 230667,
 230731,
 230741,
 230745,
 230765,
 230768,
 230769,
 230785,
 230791,
 25627,
 25695,
 330610,
 330614,
 330617,
 330621,
 330622,
 330625,
 330635,
 330667,
 330668,
 330677,
 330682,
 330683,
 330705,
 330749,
 330758,
 330786,
 330791,
 187617,
 187680,
 187700,
 187719,
 187731,
 187777,
 187785,
 171412,
 171423,
 171429,
 171479,
 171490,
 171495,
 171500,
 171503,
 171567,
 345863,
 345868,
 345887,
 345888,
 345894,
 345925,
 345967,
 138035,
 138091,
 138123,
 138186,
 245805,
 245824,
 245825,
 245826,
 245827,
 245838,
 245845,
 245846,
 245848,
 245857,
 245904,
 245927,
 245931,
 245949,
 245952,
 245961,
 245973,
 245975,
 245994,
 245998,
 191844,
 191871,
 191932,
 191958,
 191985,
 112445,
 112462,
 324820,
 324821,
 324822,
 324880,
 324909,
 324917,
 324943,
 324944,
 324997,
 224815,
 224831,
 224872,
 224897,
 224898,
 224899,
 224904,
 224920,
 224926,
 224979,
 224983,
 224991,
 253608,
 253638,
 253664,
 253665,
 253677,
 253683,
 253705,
 253719,
 253721,
 253723,
 253724,
 253734,
 253743,
 253754,
 253756,
 253759,
 253762,
 253763,
 253766,
 253794,
 353653,
 353654,
 353655,
 353677,
 353681,
 353719,
 353721,
 353734,
 353745,
 353780,
 353781,
 353782,
 353790,
 353794,
 353798,
 311237,
 311247,
 311258,
 311270,
 311314,
 311324,
 311332,
 311354,
 311356,
 126025,
 126100,
 84005,
 357801,
 357812,
 357819,
 357824,
 357863,
 357865,
 357872,
 357873,
 357878,
 357928,
 357936,
 357937,
 357938,
 357945,
 357962,
 357963,
 357982,
 357998,
 211202,
 211203,
 211264,
 211275,
 211364,
 211388,
 257802,
 257819,
 257821,
 257835,
 257850,
 257853,
 257855,
 257939,
 257987,
 257995,
 257997,
 257998,
 257999,
 291003,
 291065,
 291131,
 291133,
 291182,
 291183,
 291192,
 199623,
 199646,
 199656,
 199730,
 199792,
 53093,
 53168,
 171234,
 171258,
 171261,
 171271,
 171290,
 171339,
 171351,
 171356,
 346057,
 346109,
 346113,
 346136,
 346141,
 346147,
 346151,
 137811,
 137830,
 137872,
 137917,
 137969,
 137987,
 137988,
 246002,
 246004,
 246020,
 246037,
 246088,
 246090,
 246142,
 246144,
 246154,
 246156,
 246162,
 144809,
 144811,
 144826,
 144850,
 144862,
 144915,
 144948,
 144993,
 67453,
 272409,
 272434,
 272442,
 272447,
 272522,
 272523,
 272529,
 272531,
 272533,
 272537,
 284627,
 284635,
 284639,
 284646,
 284653,
 284658,
 284659,
 284665,
 284666,
 284707,
 284716,
 284724,
 284742,
 284743,
 284748,
 284757,
 133633,
 133641,
 133663,
 133749,
 133750,
 133772,
 133775,
 133777,
 133778,
 133780,
 150623,
 150654,
 150659,
 150682,
 150690,
 ...]

In [103]:

df_main['kickstarter'] = df_main['id'].isin(df_kickstarter_list)

/var/folders/rb/p48bcgy90nn3g9bz4kw5bh4w0000gn/T/ipykernel_6166/2466748162.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_main['kickstarter'] = df_main['id'].isin(df_kickstarter_list)

In [104]:
df_main

,id,yearpublished,min_players,max_players,playtime,min_playtime,max_playtime,min_age,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight,kickstarter
0,98401,2010.0,2.0,4.0,30.0,30.0,30.0,10,7.08333,3,15,0,1,3,2,2,1.5,False
1,98402,2011.0,2.0,5.0,30.0,30.0,30.0,8,6.34615,26,20,0,7,13,9,5,2.2,False
2,98406,2011.0,2.0,4.0,30.0,30.0,30.0,10,6.73333,9,16,3,0,0,3,1,1.0,False
3,98416,2007.0,2.0,4.0,50.0,50.0,50.0,8,6.80000,2,16,2,1,0,2,1,3.0,False
4,98417,2009.0,2.0,2.0,60.0,60.0,60.0,12,0.00000,0,10,1,2,2,0,1,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137142,298189,2020.0,3.0,7.0,120.0,30.0,120.0,7,0.00000,0,0,0,0,0,0,0,NaN,True
137143,298190,2020.0,3.0,6.0,30.0,30.0,30.0,12,6.66667,3,47,2,1,5,4,0,NaN,False
137144,298191,2022.0,2.0,5.0,80.0,30.0,80.0,8,0.00000,0,5,0,0,0,0,0,NaN,False
137145,298193,2020.0,2.0,6.0,20.0,10.0,20.0,10,7.38077,26,61,1,0,7,7,2,1.5,False
137146,298195,2020.0,1.0,4.0,120.0,60.0,120.0,14,6.66667,3,79,1,16,78,6,0,NaN,True