In [2]:
from sql_functions import get_dataframe
import pandas as pd
import Capstone_functions as sf

In [3]:
schema = "bgg_data"
main = "ml_boardgame_stats"
subdomain = "subdomain"
unique_subdomain = "unique_subdomain"
kickstarter = "clean_ks_with_bgg_id"


df_main = get_dataframe(f"SELECT * FROM {schema}.{main}")
df_marketplace = sf.avg_price_from_marketplace()
df_sub = get_dataframe(f"SELECT * FROM {schema}.{subdomain}")
df_u_sub = get_dataframe(f"SELECT * FROM {schema}.{unique_subdomain}")
df_ks = get_dataframe(f"SELECT * FROM {schema}.{kickstarter}")

In [4]:
df_3 = pd.merge(df_main, df_marketplace, how="inner", on="id")
df_3 = pd.merge(df_3, df_sub, how="left", on="id")
df_3 = pd.merge(df_3, df_u_sub, how="left", on="subdomain_id")

In [5]:
df_3 = df_3[df_3["subdomain_id"].notna()]
df_3

,id,yearpublished,min_players,max_players,min_playtime,max_playtime,min_age,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight,avg_price,subdomain_id,subdomain_name
0,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,5499.0,Family
1,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,5497.0,Strategy
2,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,4665.0,Children's
3,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,5499.0,Family
4,51203,2009.0,3.0,5.0,30.0,30.0,8,4.90000,14,29,2,1,4,4,0,NaN,24.67,4665.0,Children's
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17655,218333,2017.0,2.0,4.0,10.0,20.0,5,7.25768,4346,8229,87,255,1438,789,65,1.1077,24.93,5499.0,Family
17658,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,5497.0,Strategy
17659,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,5496.0,Thematic
17668,298060,2020.0,2.0,4.0,15.0,30.0,14,6.98775,957,2081,52,51,378,176,15,1.4667,14.48,5499.0,Family
17669,298069,2021.0,2.0,4.0,30.0,60.0,10,7.57766,4434,8218,112,452,2846,682,89,2.1685,45.57,5499.0,Family

In [6]:
df_4 = df_3.groupby('id').agg({"subdomain_name":"unique"})

In [7]:
df_5 = pd.merge(df_3, df_4, how="inner", on="id")
df_5

,id,yearpublished,min_players,max_players,min_playtime,max_playtime,min_age,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight,avg_price,subdomain_id,subdomain_name_x,subdomain_name_y
0,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,5499.0,Family,"[Family , Strategy ]"
1,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,5497.0,Strategy,"[Family , Strategy ]"
2,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,4665.0,Children's,"[Children's , Family ]"
3,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,5499.0,Family,"[Children's , Family ]"
4,51203,2009.0,3.0,5.0,30.0,30.0,8,4.90000,14,29,2,1,4,4,0,NaN,24.67,4665.0,Children's,[Children's ]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8459,218333,2017.0,2.0,4.0,10.0,20.0,5,7.25768,4346,8229,87,255,1438,789,65,1.1077,24.93,5499.0,Family,"[Children's , Family ]"
8460,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,5497.0,Strategy,"[Strategy , Thematic ]"
8461,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,5496.0,Thematic,"[Strategy , Thematic ]"
8462,298060,2020.0,2.0,4.0,15.0,30.0,14,6.98775,957,2081,52,51,378,176,15,1.4667,14.48,5499.0,Family,[Family ]
8463,298069,2021.0,2.0,4.0,30.0,60.0,10,7.57766,4434,8218,112,452,2846,682,89,2.1685,45.57,5499.0,Family,[Family ]

In [8]:
df_5 = df_5.drop(["subdomain_name_x", "subdomain_id"], axis=1)
df_5

,id,yearpublished,min_players,max_players,min_playtime,max_playtime,min_age,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight,avg_price,subdomain_name_y
0,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,"[Family , Strategy ]"
1,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,"[Family , Strategy ]"
2,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,"[Children's , Family ]"
3,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,"[Children's , Family ]"
4,51203,2009.0,3.0,5.0,30.0,30.0,8,4.90000,14,29,2,1,4,4,0,NaN,24.67,[Children's ]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8459,218333,2017.0,2.0,4.0,10.0,20.0,5,7.25768,4346,8229,87,255,1438,789,65,1.1077,24.93,"[Children's , Family ]"
8460,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,"[Strategy , Thematic ]"
8461,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,"[Strategy , Thematic ]"
8462,298060,2020.0,2.0,4.0,15.0,30.0,14,6.98775,957,2081,52,51,378,176,15,1.4667,14.48,[Family ]
8463,298069,2021.0,2.0,4.0,30.0,60.0,10,7.57766,4434,8218,112,452,2846,682,89,2.1685,45.57,[Family ]

In [9]:
df_5 = df_5.drop_duplicates("id")
df_5

,id,yearpublished,min_players,max_players,min_playtime,max_playtime,min_age,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight,avg_price,subdomain_name_y
0,98472,2011.0,3.0,7.0,60.0,60.0,10,5.54551,167,477,34,7,71,55,14,2.2143,9.55,"[Family , Strategy ]"
2,98529,2011.0,2.0,4.0,15.0,15.0,6,6.04040,248,427,24,18,42,118,22,1.0909,32.48,"[Children's , Family ]"
4,51203,2009.0,3.0,5.0,30.0,30.0,8,4.90000,14,29,2,1,4,4,0,NaN,24.67,[Children's ]
5,51250,2009.0,2.0,2.0,15.0,15.0,10,6.93672,64,98,2,9,39,21,4,1.7500,30.00,[Abstract ]
6,173074,2015.0,1.0,5.0,20.0,20.0,7,5.85268,390,1121,39,17,107,105,14,1.2143,21.07,[Children's ]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8456,218311,2017.0,1.0,6.0,30.0,90.0,12,6.63368,2374,3956,173,51,348,457,45,1.6000,13.61,"[Party , Thematic ]"
8458,218333,2017.0,2.0,4.0,10.0,20.0,5,7.25768,4346,8229,87,255,1438,789,65,1.1077,24.93,"[Children's , Family ]"
8460,218376,2018.0,2.0,4.0,60.0,90.0,13,7.52945,419,940,23,84,442,161,12,2.8333,108.15,"[Strategy , Thematic ]"
8462,298060,2020.0,2.0,4.0,15.0,30.0,14,6.98775,957,2081,52,51,378,176,15,1.4667,14.48,[Family ]
8463,298069,2021.0,2.0,4.0,30.0,60.0,10,7.57766,4434,8218,112,452,2846,682,89,2.1685,45.57,[Family ]

In [10]:
subdomain_dummy = pd.get_dummies(df_5.subdomain_name_y.apply(pd.Series).stack(), drop_first=True).sum(level=0)
subdomain_dummy

/var/folders/4q/cl23pkln7hj7tnvr0yw_yhkw0000gn/T/ipykernel_2005/136462435.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  subdomain_dummy = pd.get_dummies(df_5.subdomain_name_y.apply(pd.Series).stack(), drop_first=True).sum(level=0)

,Children's,Customizable,Family,Party,Strategy,Thematic,Wargames
0,0,0,1,0,1,0,0
2,1,0,1,0,0,0,0
4,1,0,0,0,0,0,0
5,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...
8456,0,0,0,1,0,1,0
8458,1,0,1,0,0,0,0
8460,0,0,0,0,1,1,0
8462,0,0,1,0,0,0,0
8463,0,0,1,0,0,0,0

In [11]:
df_6 = pd.concat([subdomain_dummy, df_5], axis=1)
df_6 = df_6.drop(["subdomain_name_y"], axis=1)
df_6 = df_6.drop(["max_playtime"], axis=1)
df_6

,Children's,Customizable,Family,Party,Strategy,Thematic,Wargames,id,yearpublished,min_players,...,average,user_rated,num_owned,trading,wanting,wishing,numcomments,numweights,averageweight,avg_price
0,0,0,1,0,1,0,0,98472,2011.0,3.0,...,5.54551,167,477,34,7,71,55,14,2.2143,9.55
2,1,0,1,0,0,0,0,98529,2011.0,2.0,...,6.04040,248,427,24,18,42,118,22,1.0909,32.48
4,1,0,0,0,0,0,0,51203,2009.0,3.0,...,4.90000,14,29,2,1,4,4,0,NaN,24.67
5,0,0,0,0,0,0,0,51250,2009.0,2.0,...,6.93672,64,98,2,9,39,21,4,1.7500,30.00
6,1,0,0,0,0,0,0,173074,2015.0,1.0,...,5.85268,390,1121,39,17,107,105,14,1.2143,21.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8456,0,0,0,1,0,1,0,218311,2017.0,1.0,...,6.63368,2374,3956,173,51,348,457,45,1.6000,13.61
8458,1,0,1,0,0,0,0,218333,2017.0,2.0,...,7.25768,4346,8229,87,255,1438,789,65,1.1077,24.93
8460,0,0,0,0,1,1,0,218376,2018.0,2.0,...,7.52945,419,940,23,84,442,161,12,2.8333,108.15
8462,0,0,1,0,0,0,0,298060,2020.0,2.0,...,6.98775,957,2081,52,51,378,176,15,1.4667,14.48
8463,0,0,1,0,0,0,0,298069,2021.0,2.0,...,7.57766,4434,8218,112,452,2846,682,89,2.1685,45.57

In [12]:
df_ks["id"] = df_ks["bgg_id"]
df = pd.merge(df_6, df_ks, on="id", how="inner")
df

,Children's,Customizable,Family,Party,Strategy,Thematic,Wargames,id,yearpublished,min_players,...,currency,deadline,created_at,launched_at,goal,pledged,backers_count,usd_pledged,state_changed_at,successful
0,0,0,0,0,0,1,0,244274,2019.0,1.0,...,USD,2018-12-04 04:00:00,2018-09-25 19:07:01,2018-11-12 16:00:41,10000,45633.18,882,45633.18,2018-12-04 04:00:00,True
1,0,0,0,0,1,0,0,190247,2016.0,2.0,...,USD,2016-05-18 06:59:00,2016-01-31 19:30:12,2016-04-12 13:22:48,35000,49006.00,846,49006.00,2016-05-18 06:59:03,True
2,0,0,0,0,1,0,0,43365,2009.0,3.0,...,USD,2015-02-15 16:30:02,2014-06-27 21:16:46,2015-02-05 16:30:02,5000,29851.00,405,29851.00,2015-02-15 16:30:16,True
3,0,0,0,0,1,0,0,2960,2002.0,2.0,...,USD,2012-09-14 16:42:26,2012-08-08 16:39:12,2012-08-15 16:42:26,10000,15169.26,358,15169.26,2012-09-14 16:42:26,True
4,0,0,0,0,0,1,0,281526,2022.0,1.0,...,USD,2019-10-04 05:00:00,2019-08-07 17:02:49,2019-09-10 15:00:04,54000,260938.00,3934,260938.00,2019-10-04 05:00:00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,0,0,0,0,1,0,1,178550,2016.0,2.0,...,USD,2015-07-03 00:00:00,2015-04-30 17:58:18,2015-06-02 15:23:48,35000,43268.00,618,43268.00,2015-07-03 00:00:12,True
233,0,0,0,0,0,0,1,178572,2015.0,2.0,...,GBP,2015-06-18 19:00:00,2014-07-17 11:41:29,2015-05-29 18:00:45,5000,7460.00,216,11454.49,2015-06-18 19:00:12,True
234,0,0,0,0,1,0,0,286160,2020.0,2.0,...,USD,2019-10-19 04:59:00,2019-08-22 19:12:53,2019-09-16 11:52:51,30000,239972.00,3164,239972.00,2019-10-19 04:59:00,True
235,0,0,1,0,1,0,0,4396,2002.0,2.0,...,USD,2013-03-06 02:16:47,2013-01-08 22:52:39,2013-02-04 02:16:47,15000,22559.00,679,22559.00,2013-03-06 02:16:47,True
236,0,0,0,0,0,0,1,318322,2021.0,1.0,...,USD,2020-10-10 20:00:00,2020-08-08 14:33:53,2020-09-26 16:58:31,1776,33106.00,347,33106.00,2020-10-10 20:00:00,True

In [13]:
df.isnull().sum()

Children's          0
Customizable        0
Family              0
Party               0
Strategy            0
Thematic            0
Wargames            0
id                  0
yearpublished       0
min_players         0
max_players         0
min_playtime        1
min_age             0
average             0
user_rated          0
num_owned           0
trading             0
wanting             0
wishing             0
numcomments         0
numweights          0
averageweight       0
avg_price           0
bgg_id              0
country             0
currency            0
deadline            0
created_at          0
launched_at         0
goal                0
pledged             0
backers_count       0
usd_pledged         0
state_changed_at    0
successful          0
dtype: int64

In [14]:
df["min_playtime"] = df["min_playtime"].fillna(0)

In [15]:
df.columns = df.columns.str.replace(" ", "")
df.columns

Index(['Children's', 'Customizable', 'Family', 'Party', 'Strategy', 'Thematic',
       'Wargames', 'id', 'yearpublished', 'min_players', 'max_players',
       'min_playtime', 'min_age', 'average', 'user_rated', 'num_owned',
       'trading', 'wanting', 'wishing', 'numcomments', 'numweights',
       'averageweight', 'avg_price', 'bgg_id', 'country', 'currency',
       'deadline', 'created_at', 'launched_at', 'goal', 'pledged',
       'backers_count', 'usd_pledged', 'state_changed_at', 'successful'],
      dtype='object')

In [16]:
X = df[["Children's", "Customizable", "Family", "Party", "Strategy", "Thematic", "Wargames", "min_players", "max_players", "min_playtime", "min_age", "wanting", "wishing", "averageweight", "avg_price"]]

In [17]:
y = df.usd_pledged

In [18]:
# import the statsmodels.api module
import statsmodels.api as sm
X = sm.add_constant(X)

In [19]:
# create an OLS model
our_model = sm.OLS(y, X)

# use the data to calculate the intercept and slope
model_results = our_model.fit()

# return the output of the model
model_results.summary() # summary contains eg. 'const' (intercept) and 'slope' of the regression equation.

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            usd_pledged   R-squared:                       0.415
Model:                            OLS   Adj. R-squared:                  0.375
Method:                 Least Squares   F-statistic:                     10.45
Date:                Tue, 12 Jul 2022   Prob (F-statistic):           8.60e-19
Time:                        10:02:57   Log-Likelihood:                -3232.1
No. Observations:                 237   AIC:                             6496.
Df Residuals:                     221   BIC:                             6552.
Df Model:                          15
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const          6.347e+04   8.64e+04      0.734      0.463   -1.07e+05    2.34e+05
Children's     3260.0737   1.14e+05      0.028      0.977   -2.22e+05    2.29e+05
Customizable  -1.249e+04   2.12e+05     -0.059      0.953    -4.3e+05    4.05e+05
Family        -2611.5787   4.49e+04     -0.058      0.954   -9.12e+04    8.59e+04
Party          4.138e+05   7.81e+04      5.302      0.000     2.6e+05    5.68e+05
Strategy       6172.0007   4.37e+04      0.141      0.888   -7.99e+04    9.22e+04
Thematic       4.709e+04   3.97e+04      1.187      0.236   -3.11e+04    1.25e+05
Wargames       -5.14e+04   4.57e+04     -1.124      0.262   -1.42e+05    3.87e+04
min_players   -5897.1720   2.18e+04     -0.271      0.787   -4.88e+04     3.7e+04
max_players   -1.518e+04   6104.983     -2.486      0.014   -2.72e+04   -3144.324
min_playtime   -300.9184    236.593     -1.272      0.205    -767.186     165.349
min_age       -6562.2367   4695.657     -1.398      0.164   -1.58e+04    2691.758
wanting       -1467.9140    272.590     -5.385      0.000   -2005.122    -930.706
wishing         318.0691     41.972      7.578      0.000     235.352     400.786
averageweight  4.246e+04   2.77e+04      1.535      0.126   -1.21e+04     9.7e+04
avg_price      1327.1046    306.426      4.331      0.000     723.214    1930.995
==============================================================================
Omnibus:                      295.664   Durbin-Watson:                   2.154
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            24514.883
Skew:                           5.225   Prob(JB):                         0.00
Kurtosis:                      51.717   Cond. No.                     1.29e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:
X = df[["wanting", "wishing", "avg_price", "Party", "max_players"]]
X.describe()

          wanting      wishing   avg_price       Party  max_players
count  237.000000   237.000000  237.000000  237.000000   237.000000
mean    74.189873   409.379747   61.001097    0.059072     4.616034
std    111.650682   709.476215   56.650911    0.236258     3.093226
min      0.000000     2.000000    6.030000    0.000000     1.000000
25%     13.000000    66.000000   29.220000    0.000000     3.000000
50%     33.000000   172.000000   44.900000    0.000000     4.000000
75%     83.000000   468.000000   72.100000    0.000000     6.000000
max    834.000000  5612.000000  385.000000    1.000000    30.000000

In [26]:
# create an OLS model
our_model = sm.OLS(y, X)

# use the data to calculate the intercept and slope
model_results = our_model.fit()

# return the output of the model
model_results.summary() # summary contains eg. 'const' (intercept) and 'slope' of the regression equation.

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:            usd_pledged   R-squared (uncentered):                   0.477
Model:                            OLS   Adj. R-squared (uncentered):              0.466
Method:                 Least Squares   F-statistic:                              42.40
Date:                Tue, 12 Jul 2022   Prob (F-statistic):                    6.41e-31
Time:                        10:08:01   Log-Likelihood:                         -3239.2
No. Observations:                 237   AIC:                                      6488.
Df Residuals:                     232   BIC:                                      6506.
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
wanting     -1410.4002    267.134     -5.280      0.000   -1936.719    -884.081
wishing       333.1579     41.443      8.039      0.000     251.504     414.812
avg_price    1343.7722    238.359      5.638      0.000     874.148    1813.397
Party        3.431e+05   6.79e+04      5.053      0.000    2.09e+05    4.77e+05
max_players -6425.7218   3795.090     -1.693      0.092   -1.39e+04    1051.523
==============================================================================
Omnibus:                      296.508   Durbin-Watson:                   2.105
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            23994.178
Skew:                           5.266   Prob(JB):                         0.00
Kurtosis:                      51.155   Cond. No.                     4.11e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 4.11e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [22]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [28]:
# X = df[["wanting", "wishing", "avg_price", "Party"]]
predicted_pledged_amount = regr.predict([[20, 500, 30, 0]])
predicted_pledged_amount

/opt/homebrew/Caskroom/miniconda/base/envs/nf_sql/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([172102.87873101])